### ISSUE TITLE
Elixir 1.17 & Erlang 27 support

### ISSUE THREAD

**Issue by esambo** [zmstone/snappyer#10] opened 2024-06-14 15:32 UTC
It is not compiling for me:
```
** (Mix) Could not compile dependency :snappyer, "~/.asdf/installs/elixir/1.17.0-otp-27/.mix/elixir/1-17/rebar3 bare compile --paths ~/projects/podium/azeroth/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile snappyer --force", update it with "mix deps.update snappyer" or clean it with "mix deps.clean snappyer"
```

**Comment by bclaud** [comment] 2024-06-19 17:01
It's building with the latest rebar3 version. The problem is the projects that depends on snappyer are locked. Check the mentioned PR above.

```sh
snappyer on  master via  via ❄️  impure (cobranca_ms-env) 
❯ make compile
===> Fetching pc v1.15.0
===> Analyzing applications...
===> Compiling pc
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling snappyer

snappyer on  master via  via ❄️  impure (cobranca_ms-env) 
❯ rebar3 --version
rebar 3.23.0 on Erlang/OTP 27 Erts 15.0
```

**Comment by slashmili** [comment] 2024-06-24 08:56
From what I understood the issue is related to `pc` https://github.com/blt/port_compiler/issues/82

`pc` has a already been [patched](https://github.com/blt/port_compiler/pull/80) but the issue is that some of us are getting older version of  `pc` when we get the dependencies.

If there is a way to fix the dependency version at here https://github.com/zmstone/snappyer/blob/master/rebar.config#L7 would be great!

**Comment by mathieurousseau** [comment] 2024-10-08 16:30
As you're using asdf (replace with the right version of asdf you are using in the rebar3 path): 

```bash
cd deps/snappyer/
$HOME/.asdf/installs/elixir/1.17.2-otp-27/.mix/elixir/1-17/rebar3 plugins upgrade --all
cd ../..
mix compile
```

**Comment by zmstone** [comment] 2024-10-09 09:54
Thank you for the tips @mathieurousseau

**Comment by zmstone** [comment] 2024-10-09 09:54
~~I am closing this issue here, because~~

1. snappyer does not pin `pc` version. ~~one should pin or override `pc` version in the wrapping project~~.
2. it has been removed as a dependency for `brod` starting from version `4.0`.
3. it has been removed as a dependency for `kafak_protocol` from version `4.0`.

**Comment by slashmili** [comment] 2024-10-09 10:18
Since `snappyer` is using `pc` and not the wrapper project, I'd say the pinning should be done here. No?

**Closed** 2024-10-09 10:40 UTC
